import { createAction, props } from "@ngrx/store";
import { SearchResult } from "../../applications/models/search.model";
import { HumanTaskDef } from "../models/humantaskdef.model";
import { HumanTaskInstance } from "../models/humantaskinstance.model";
import { SearchHumanTaskDefsResult } from "../models/searchhumantaskdef.model";

export const startGet = createAction('[HumanTaskDef] START_GET_HUMANTASKDEF', props<{ id: string }>());
export const completeGet = createAction('[HumanTaskDef] COMPLETE_GET_HUMANTASKDEF', props<{ content: HumanTaskDef }>());
export const errorGet = createAction('[HumanTaskDef] ERROR_GET_HUMANTASKDEF');
export const startSearch = createAction('[HumanTaskDef] START_SEARCH_HUMANTASKDEF', props<{ order: string, direction: string, count: number, startIndex: number }>());
export const completeSearch = createAction('[HumanTaskDef] COMPLETE_SEARCH_HUMANTASKDEF', props<{ content: SearchHumanTaskDefsResult }>());
export const errorSearch = createAction('[HumanTaskDef] ERROR_SEARCH_HUMANTASKDEF');
export const startGetAll = createAction('[HumanTaskDef] START_GET_ALL_HUMANTASKDEF');
export const completeGetAll = createAction('[HumanTaskDef] COMPLETE_GET_ALL_HUMANTASKDEF', props<{ content: HumanTaskDef[] }>());
export const errorGetAll = createAction('[HumanTaskDef] ERROR_GET_ALL_HUMANTASKDEF');
export const startGetInstance = createAction('[HumanTaskInstance] START_GET_HUMANTASKINSTANCE', props<{ id: string }>());
export const completeGetInstance = createAction('[HumanTaskInstance] COMPLETE_GET_HUMANTASKINSTANCE', props<{ rendering: any, task: HumanTaskInstance }>());
export const errorGetInstance = createAction('[HumanTaskInstance] ERROR_GET_HUMANTASKINSTANCE');
export const startSubmitInstance = createAction('[HumanTaskInstance] START_SUBMIT_HUMANTASKINSTANCE', props<{ id: string, operationParameters: any }>());
export const errorSubmitInstance = createAction('[HumanTaskInstance] ERROR_SUBMIT_HUMANTASK_INSTANCE');
export const completeSubmitInstance = createAction('[HumanTaskInstance] COMPLETE_SUBMIT_HUMANTASK_INSTANCE');
export const startSearchInstances = createAction('[HumanTaskInstance] START_SEARCH_HUMANTASKINSTANCE', props<{ order: string, direction: string, count: number, startIndex: number }>());
export const errorSearchInstances = createAction('[HumanTaskInstance] ERROR_SEARCH_HUMANTASKINSTANCE');
export const completeSearchInstances = createAction('[HumanTaskInstance] COMPLETE_SEARCH_HUMANTASKINSTANCE', props <{ content: SearchResult<HumanTaskInstance> }>());
