// Copyright (c) SimpleIdServer. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
using SimpleIdServer.Did.Crypto;
using SimpleIdServer.Did.Key;
using SimpleIdServer.WalletClient;
using System.Text.Json;

// var publicKey = GenerateDidKey();
var publicKey = "did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9Kbrz1hh3CRY4pejtRCZ81CZj8PERW5ZtX2MxSEevzFx8knNYgxZm4emyBxZ8pyB2FipG8ciRVnWQeuRu7oJqfpkoQjqhsAzw5h8u5RPG6XEZSarcafMQumUrGtJc3twQRc9J";
var serializedPrivateKey = System.IO.File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(), "privatekey.json"));
var privateKey = SignatureKeySerializer.Deserialize(serializedPrivateKey);

// InTimeCredential();
// DeferredCredential();
// PreAuthorisedInTimeCredential();
// PreAuthorisedAndDeferredCredential();
VerifiablePresentationExchange();

void InTimeCredential()
{
    var intentData = "openid-credential-offer://?credential_offer_uri=https%3A%2F%2Fapi-conformance.ebsi.eu%2Fconformance%2Fv3%2Fissuer-mock%2Foffers%2Fffeb73a0-a951-4442-8439-7b51265437ee";
    var uri = Uri.TryCreate(intentData, UriKind.Absolute, out Uri r);
    var q = r.Query.TrimStart('?').Split('&').Select(t => t.Split('=')).ToDictionary(r => r[0], r => r[1]);
    var resolver = VerifiableCredentialOfferResolverFactory.Build();
    var vc = resolver.Resolve(q, publicKey, privateKey, CancellationToken.None).Result;
    Console.WriteLine(vc.Status);
}

void DeferredCredential()
{
    var intentData = "openid-credential-offer://?credential_offer_uri=https%3A%2F%2Fapi-conformance.ebsi.eu%2Fconformance%2Fv3%2Fissuer-mock%2Foffers%2F540d4b76-9399-410d-b79f-0de227b506ef";
    var uri = Uri.TryCreate(intentData, UriKind.Absolute, out Uri r);
    var q = r.Query.TrimStart('?').Split('&').Select(t => t.Split('=')).ToDictionary(r => r[0], r => r[1]);
    var resolver = VerifiableCredentialOfferResolverFactory.Build();
    var vc = resolver.Resolve(q, publicKey, privateKey, CancellationToken.None).Result;
    Thread.Sleep(6000);
    vc = vc.Retry(CancellationToken.None).Result;
    Console.WriteLine(vc.Status);
}

void PreAuthorisedInTimeCredential()
{
    const string pin = "6267";
    var intentData = "openid-credential-offer://?credential_offer_uri=https%3A%2F%2Fapi-conformance.ebsi.eu%2Fconformance%2Fv3%2Fissuer-mock%2Foffers%2F9f7626f4-d4d5-4932-b81f-658e2d7904e3";
    var uri = Uri.TryCreate(intentData, UriKind.Absolute, out Uri r);
    var q = r.Query.TrimStart('?').Split('&').Select(t => t.Split('=')).ToDictionary(r => r[0], r => r[1]);
    var resolver = VerifiableCredentialOfferResolverFactory.Build();
    var vc = resolver.Resolve(q, publicKey, privateKey, pin, CancellationToken.None).Result;
    Console.WriteLine(vc.Status);
}

void PreAuthorisedAndDeferredCredential()
{
    const string pin = "6267";
    var intentData = "openid-credential-offer://?credential_offer_uri=https%3A%2F%2Fapi-conformance.ebsi.eu%2Fconformance%2Fv3%2Fissuer-mock%2Foffers%2Fef87610b-f10e-444d-b5a6-17aed1286bcb";
    var uri = Uri.TryCreate(intentData, UriKind.Absolute, out Uri r);
    var q = r.Query.TrimStart('?').Split('&').Select(t => t.Split('=')).ToDictionary(r => r[0], r => r[1]);
    var resolver = VerifiableCredentialOfferResolverFactory.Build();
    var vc = resolver.Resolve(q, publicKey, privateKey, pin, CancellationToken.None).Result;
    Thread.Sleep(6000);
    vc = vc.Retry(CancellationToken.None).Result;
    Console.WriteLine(vc.Status);
}

void VerifiablePresentationExchange()
{
    var intentData = "openid-credential-offer://?credential_offer_uri=https%3A%2F%2Fapi-conformance.ebsi.eu%2Fconformance%2Fv3%2Fissuer-mock%2Foffers%2F1e4aec19-ad1c-4838-96d9-6fd404c1cd14";
    var uri = Uri.TryCreate(intentData, UriKind.Absolute, out Uri r);
    var q = r.Query.TrimStart('?').Split('&').Select(t => t.Split('=')).ToDictionary(r => r[0], r => r[1]);
    var resolver = VerifiableCredentialOfferResolverFactory.Build(storedVcRecords: new List<StoredVcRecord>
    {
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDE2NDgsImV4cCI6MTcyNDUyODA1MywianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSNjNmMyZWVkMC05YWM5LTRhMTEtOGI0Yi00YmQxZWJiNWYyMzkiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0MTY0OCwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlI2M2YzJlZWQwLTlhYzktNGExMS04YjRiLTRiZDFlYmI1ZjIzOSIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldFNhbWVBdXRob3Jpc2VkSW5UaW1lIl0sImlzc3VlciI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEIiwiaXNzdWFuY2VEYXRlIjoiMjAyNC0wOC0yM1QxOTozNDowOFoiLCJpc3N1ZWQiOiIyMDI0LTA4LTIzVDE5OjM0OjA4WiIsInZhbGlkRnJvbSI6IjIwMjQtMDgtMjNUMTk6MzQ6MDhaIiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA4LTI0VDE5OjM0OjEzWiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImlkIjoiZGlkOmtleTp6MmRtekQ4MWNnUHg4VmtpN0pidXVNbUZZcldQZ1lveXR5a1VaM2V5cWh0MWo5S2JyejFoaDNDUlk0cGVqdFJDWjgxQ1pqOFBFUlc1WnRYMk14U0VldnpGeDhrbk5ZZ3habTRlbXlCeFo4cHlCMkZpcEc4Y2lSVm5XUWV1UnU3b0pxZnBrb1FqcWhzQXp3NWg4dTVSUEc2WEVaU2FyY2FmTVF1bVVyR3RKYzN0d1FSYzlKIn0sImNyZWRlbnRpYWxTY2hlbWEiOnsiaWQiOiJodHRwczovL2FwaS1jb25mb3JtYW5jZS5lYnNpLmV1L3RydXN0ZWQtc2NoZW1hcy1yZWdpc3RyeS92My9zY2hlbWFzL3ozTWdVRlVrYjcyMnVxNHgzZHY1eUFKbW5ObXpERmVLNVVDOHg4M1FvZUxKTSIsInR5cGUiOiJGdWxsSnNvblNjaGVtYVZhbGlkYXRvcjIwMjEifSwidGVybXNPZlVzZSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1pc3N1ZXJzLXJlZ2lzdHJ5L3Y1L2lzc3VlcnMvZGlkOmVic2k6empIWmpKNFN5N3I5MkJ4WHpGR3M3cUQvYXR0cmlidXRlcy9iY2RiNmJjOTUyYzhjODk3Y2ExZTYwNWZjZTI1ZjgyNjA0Yzc2YzE2ZDQ3OTc3MDAxNGI3YjI2MmI5M2MwMjUwIiwidHlwZSI6Iklzc3VhbmNlQ2VydGlmaWNhdGUifX19.xhgDWeBW43HLn4zPhIrfcxVyOkbP26X7-AF_KBKiU2WCPqF-enzbrUyETqCJqwPcuYb2Y9qtoj5LJ0ZtdvamXQ"
        },
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDE3OTEsImV4cCI6MTcyNDUyODE5NiwianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSNiMTU4MzkwYi0xMGQxLTQyNzItOWE1Mi1mZjY5MzIzMmQ4MjMiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0MTc5MSwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlI2IxNTgzOTBiLTEwZDEtNDI3Mi05YTUyLWZmNjkzMjMyZDgyMyIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldFNhbWVBdXRob3Jpc2VkRGVmZXJyZWQiXSwiaXNzdWVyIjoiZGlkOmVic2k6empIWmpKNFN5N3I5MkJ4WHpGR3M3cUQiLCJpc3N1YW5jZURhdGUiOiIyMDI0LTA4LTIzVDE5OjM2OjMxWiIsImlzc3VlZCI6IjIwMjQtMDgtMjNUMTk6MzY6MzFaIiwidmFsaWRGcm9tIjoiMjAyNC0wOC0yM1QxOTozNjozMVoiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjQtMDgtMjRUMTk6MzY6MzZaIiwiY3JlZGVudGlhbFN1YmplY3QiOnsiaWQiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoifSwiY3JlZGVudGlhbFNjaGVtYSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1zY2hlbWFzLXJlZ2lzdHJ5L3YzL3NjaGVtYXMvejNNZ1VGVWtiNzIydXE0eDNkdjV5QUptbk5tekRGZUs1VUM4eDgzUW9lTEpNIiwidHlwZSI6IkZ1bGxKc29uU2NoZW1hVmFsaWRhdG9yMjAyMSJ9LCJ0ZXJtc09mVXNlIjp7ImlkIjoiaHR0cHM6Ly9hcGktY29uZm9ybWFuY2UuZWJzaS5ldS90cnVzdGVkLWlzc3VlcnMtcmVnaXN0cnkvdjUvaXNzdWVycy9kaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRC9hdHRyaWJ1dGVzL2JjZGI2YmM5NTJjOGM4OTdjYTFlNjA1ZmNlMjVmODI2MDRjNzZjMTZkNDc5NzcwMDE0YjdiMjYyYjkzYzAyNTAiLCJ0eXBlIjoiSXNzdWFuY2VDZXJ0aWZpY2F0ZSJ9fX0.NCqPBGSc9d-O89S9wA94Kzcec62DX6AxYaCXeP7l20nVIHJ6kYpDTyfuN-pBYpxRKrwt9O2ZdKHu3RdYujej0g"
        },
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDE4OTEsImV4cCI6MTcyNDUyODI5NiwianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSM1OGY3MmNlMy02MzkxLTRjY2YtOGE2Ni04YjUwMGQ4MjMxZjAiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0MTg5MSwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlIzU4ZjcyY2UzLTYzOTEtNGNjZi04YTY2LThiNTAwZDgyMzFmMCIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldFNhbWVQcmVBdXRob3Jpc2VkSW5UaW1lIl0sImlzc3VlciI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEIiwiaXNzdWFuY2VEYXRlIjoiMjAyNC0wOC0yM1QxOTozODoxMVoiLCJpc3N1ZWQiOiIyMDI0LTA4LTIzVDE5OjM4OjExWiIsInZhbGlkRnJvbSI6IjIwMjQtMDgtMjNUMTk6Mzg6MTFaIiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA4LTI0VDE5OjM4OjE2WiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImlkIjoiZGlkOmtleTp6MmRtekQ4MWNnUHg4VmtpN0pidXVNbUZZcldQZ1lveXR5a1VaM2V5cWh0MWo5S2JyejFoaDNDUlk0cGVqdFJDWjgxQ1pqOFBFUlc1WnRYMk14U0VldnpGeDhrbk5ZZ3habTRlbXlCeFo4cHlCMkZpcEc4Y2lSVm5XUWV1UnU3b0pxZnBrb1FqcWhzQXp3NWg4dTVSUEc2WEVaU2FyY2FmTVF1bVVyR3RKYzN0d1FSYzlKIn0sImNyZWRlbnRpYWxTY2hlbWEiOnsiaWQiOiJodHRwczovL2FwaS1jb25mb3JtYW5jZS5lYnNpLmV1L3RydXN0ZWQtc2NoZW1hcy1yZWdpc3RyeS92My9zY2hlbWFzL3ozTWdVRlVrYjcyMnVxNHgzZHY1eUFKbW5ObXpERmVLNVVDOHg4M1FvZUxKTSIsInR5cGUiOiJGdWxsSnNvblNjaGVtYVZhbGlkYXRvcjIwMjEifSwidGVybXNPZlVzZSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1pc3N1ZXJzLXJlZ2lzdHJ5L3Y1L2lzc3VlcnMvZGlkOmVic2k6empIWmpKNFN5N3I5MkJ4WHpGR3M3cUQvYXR0cmlidXRlcy9iY2RiNmJjOTUyYzhjODk3Y2ExZTYwNWZjZTI1ZjgyNjA0Yzc2YzE2ZDQ3OTc3MDAxNGI3YjI2MmI5M2MwMjUwIiwidHlwZSI6Iklzc3VhbmNlQ2VydGlmaWNhdGUifX19.xcuzwDvpXOJ4itTj7FV2WwbMt-sQF4kRRy2xnrYZ2vTPd2K85uUpDdGnmlSCZJB73sMzvOdyDDGm4PFE2hmXtA"
        },
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDE5NjgsImV4cCI6MTcyNDUyODM3MywianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSM1OWNlOWJmMy01ZDk4LTRlOTEtYTEzZi1lNTAxZDJmMDFhNTgiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0MTk2OCwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlIzU5Y2U5YmYzLTVkOTgtNGU5MS1hMTNmLWU1MDFkMmYwMWE1OCIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldFNhbWVQcmVBdXRob3Jpc2VkRGVmZXJyZWQiXSwiaXNzdWVyIjoiZGlkOmVic2k6empIWmpKNFN5N3I5MkJ4WHpGR3M3cUQiLCJpc3N1YW5jZURhdGUiOiIyMDI0LTA4LTIzVDE5OjM5OjI4WiIsImlzc3VlZCI6IjIwMjQtMDgtMjNUMTk6Mzk6MjhaIiwidmFsaWRGcm9tIjoiMjAyNC0wOC0yM1QxOTozOToyOFoiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjQtMDgtMjRUMTk6Mzk6MzNaIiwiY3JlZGVudGlhbFN1YmplY3QiOnsiaWQiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoifSwiY3JlZGVudGlhbFNjaGVtYSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1zY2hlbWFzLXJlZ2lzdHJ5L3YzL3NjaGVtYXMvejNNZ1VGVWtiNzIydXE0eDNkdjV5QUptbk5tekRGZUs1VUM4eDgzUW9lTEpNIiwidHlwZSI6IkZ1bGxKc29uU2NoZW1hVmFsaWRhdG9yMjAyMSJ9LCJ0ZXJtc09mVXNlIjp7ImlkIjoiaHR0cHM6Ly9hcGktY29uZm9ybWFuY2UuZWJzaS5ldS90cnVzdGVkLWlzc3VlcnMtcmVnaXN0cnkvdjUvaXNzdWVycy9kaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRC9hdHRyaWJ1dGVzL2JjZGI2YmM5NTJjOGM4OTdjYTFlNjA1ZmNlMjVmODI2MDRjNzZjMTZkNDc5NzcwMDE0YjdiMjYyYjkzYzAyNTAiLCJ0eXBlIjoiSXNzdWFuY2VDZXJ0aWZpY2F0ZSJ9fX0.AtxYnTOVeqVOk3h_B7BQ4xsgS-zsAn0UKi3JzfbAb0mkRSg1mPvNSDwyqiaz-UWxsX85h2AIrQeo7Ed6_bXVtw"
        },
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDM3MjEsImV4cCI6MTcyNDUzMDEyNiwianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSM2MGZlNDU3My1jODg1LTRmNGYtYjk5NC0yYmI1ODEyMDNmMWQiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0MzcyMSwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlIzYwZmU0NTczLWM4ODUtNGY0Zi1iOTk0LTJiYjU4MTIwM2YxZCIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldENyb3NzQXV0aG9yaXNlZEluVGltZSJdLCJpc3N1ZXIiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsImlzc3VhbmNlRGF0ZSI6IjIwMjQtMDgtMjNUMjA6MDg6NDFaIiwiaXNzdWVkIjoiMjAyNC0wOC0yM1QyMDowODo0MVoiLCJ2YWxpZEZyb20iOiIyMDI0LTA4LTIzVDIwOjA4OjQxWiIsImV4cGlyYXRpb25EYXRlIjoiMjAyNC0wOC0yNFQyMDowODo0NloiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDprZXk6ejJkbXpEODFjZ1B4OFZraTdKYnV1TW1GWXJXUGdZb3l0eWtVWjNleXFodDFqOUticnoxaGgzQ1JZNHBlanRSQ1o4MUNaajhQRVJXNVp0WDJNeFNFZXZ6Rng4a25OWWd4Wm00ZW15QnhaOHB5QjJGaXBHOGNpUlZuV1FldVJ1N29KcWZwa29RanFoc0F6dzVoOHU1UlBHNlhFWlNhcmNhZk1RdW1Vckd0SmMzdHdRUmM5SiJ9LCJjcmVkZW50aWFsU2NoZW1hIjp7ImlkIjoiaHR0cHM6Ly9hcGktY29uZm9ybWFuY2UuZWJzaS5ldS90cnVzdGVkLXNjaGVtYXMtcmVnaXN0cnkvdjMvc2NoZW1hcy96M01nVUZVa2I3MjJ1cTR4M2R2NXlBSm1uTm16REZlSzVVQzh4ODNRb2VMSk0iLCJ0eXBlIjoiRnVsbEpzb25TY2hlbWFWYWxpZGF0b3IyMDIxIn0sInRlcm1zT2ZVc2UiOnsiaWQiOiJodHRwczovL2FwaS1jb25mb3JtYW5jZS5lYnNpLmV1L3RydXN0ZWQtaXNzdWVycy1yZWdpc3RyeS92NS9pc3N1ZXJzL2RpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEL2F0dHJpYnV0ZXMvYmNkYjZiYzk1MmM4Yzg5N2NhMWU2MDVmY2UyNWY4MjYwNGM3NmMxNmQ0Nzk3NzAwMTRiN2IyNjJiOTNjMDI1MCIsInR5cGUiOiJJc3N1YW5jZUNlcnRpZmljYXRlIn19fQ.0wjzqSDMTCoaNppGh3BcGAK-63cYyHEvOqHt5x7u-II-bgo8qWZw1E0Ocd1fV9xV2YXUm4o8GVyw4M8Us_MR2A"
        },
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDM4MjksImV4cCI6MTcyNDUzMDIzNCwianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSM4OGNiMDNlYS0wZGVkLTQ5ZDUtOGJmYS04MDBmZjU1Y2M4YjYiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0MzgyOSwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlIzg4Y2IwM2VhLTBkZWQtNDlkNS04YmZhLTgwMGZmNTVjYzhiNiIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldENyb3NzQXV0aG9yaXNlZERlZmVycmVkIl0sImlzc3VlciI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEIiwiaXNzdWFuY2VEYXRlIjoiMjAyNC0wOC0yM1QyMDoxMDoyOVoiLCJpc3N1ZWQiOiIyMDI0LTA4LTIzVDIwOjEwOjI5WiIsInZhbGlkRnJvbSI6IjIwMjQtMDgtMjNUMjA6MTA6MjlaIiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA4LTI0VDIwOjEwOjM0WiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImlkIjoiZGlkOmtleTp6MmRtekQ4MWNnUHg4VmtpN0pidXVNbUZZcldQZ1lveXR5a1VaM2V5cWh0MWo5S2JyejFoaDNDUlk0cGVqdFJDWjgxQ1pqOFBFUlc1WnRYMk14U0VldnpGeDhrbk5ZZ3habTRlbXlCeFo4cHlCMkZpcEc4Y2lSVm5XUWV1UnU3b0pxZnBrb1FqcWhzQXp3NWg4dTVSUEc2WEVaU2FyY2FmTVF1bVVyR3RKYzN0d1FSYzlKIn0sImNyZWRlbnRpYWxTY2hlbWEiOnsiaWQiOiJodHRwczovL2FwaS1jb25mb3JtYW5jZS5lYnNpLmV1L3RydXN0ZWQtc2NoZW1hcy1yZWdpc3RyeS92My9zY2hlbWFzL3ozTWdVRlVrYjcyMnVxNHgzZHY1eUFKbW5ObXpERmVLNVVDOHg4M1FvZUxKTSIsInR5cGUiOiJGdWxsSnNvblNjaGVtYVZhbGlkYXRvcjIwMjEifSwidGVybXNPZlVzZSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1pc3N1ZXJzLXJlZ2lzdHJ5L3Y1L2lzc3VlcnMvZGlkOmVic2k6empIWmpKNFN5N3I5MkJ4WHpGR3M3cUQvYXR0cmlidXRlcy9iY2RiNmJjOTUyYzhjODk3Y2ExZTYwNWZjZTI1ZjgyNjA0Yzc2YzE2ZDQ3OTc3MDAxNGI3YjI2MmI5M2MwMjUwIiwidHlwZSI6Iklzc3VhbmNlQ2VydGlmaWNhdGUifX19.IFGweWZoF225i7kjJzKT6oAt-feaWr8qwdwi82K7ZqSxPbfowrNXiGuKAUOD0KH8sGARzjLb1LV5kS-FnvUmGw"
        },
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDM5NTIsImV4cCI6MTcyNDUzMDM1NywianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSNiNDZlYTM4Zi00ZmI0LTQ1OTktOTcyNy0yNjJjNTFlN2FiZTAiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0Mzk1MiwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlI2I0NmVhMzhmLTRmYjQtNDU5OS05NzI3LTI2MmM1MWU3YWJlMCIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldENyb3NzUHJlQXV0aG9yaXNlZEluVGltZSJdLCJpc3N1ZXIiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsImlzc3VhbmNlRGF0ZSI6IjIwMjQtMDgtMjNUMjA6MTI6MzJaIiwiaXNzdWVkIjoiMjAyNC0wOC0yM1QyMDoxMjozMloiLCJ2YWxpZEZyb20iOiIyMDI0LTA4LTIzVDIwOjEyOjMyWiIsImV4cGlyYXRpb25EYXRlIjoiMjAyNC0wOC0yNFQyMDoxMjozN1oiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDprZXk6ejJkbXpEODFjZ1B4OFZraTdKYnV1TW1GWXJXUGdZb3l0eWtVWjNleXFodDFqOUticnoxaGgzQ1JZNHBlanRSQ1o4MUNaajhQRVJXNVp0WDJNeFNFZXZ6Rng4a25OWWd4Wm00ZW15QnhaOHB5QjJGaXBHOGNpUlZuV1FldVJ1N29KcWZwa29RanFoc0F6dzVoOHU1UlBHNlhFWlNhcmNhZk1RdW1Vckd0SmMzdHdRUmM5SiJ9LCJjcmVkZW50aWFsU2NoZW1hIjp7ImlkIjoiaHR0cHM6Ly9hcGktY29uZm9ybWFuY2UuZWJzaS5ldS90cnVzdGVkLXNjaGVtYXMtcmVnaXN0cnkvdjMvc2NoZW1hcy96M01nVUZVa2I3MjJ1cTR4M2R2NXlBSm1uTm16REZlSzVVQzh4ODNRb2VMSk0iLCJ0eXBlIjoiRnVsbEpzb25TY2hlbWFWYWxpZGF0b3IyMDIxIn0sInRlcm1zT2ZVc2UiOnsiaWQiOiJodHRwczovL2FwaS1jb25mb3JtYW5jZS5lYnNpLmV1L3RydXN0ZWQtaXNzdWVycy1yZWdpc3RyeS92NS9pc3N1ZXJzL2RpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEL2F0dHJpYnV0ZXMvYmNkYjZiYzk1MmM4Yzg5N2NhMWU2MDVmY2UyNWY4MjYwNGM3NmMxNmQ0Nzk3NzAwMTRiN2IyNjJiOTNjMDI1MCIsInR5cGUiOiJJc3N1YW5jZUNlcnRpZmljYXRlIn19fQ.oNPdLoxpA6XUZprxHC8Rd5JrI7m_0AM43G3c-2qXGsumB6zqw-8p1QMn_1glQ2Z1HR87IMQYqL0bpU8f9GUGdw"
        },
        new StoredVcRecord
        {
            Format = "jwt_vc",
            SerializedVc = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2cifQ.eyJpYXQiOjE3MjQ0NDQwMzIsImV4cCI6MTcyNDUzMDQzNywianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSM4MWI4YTdkNC1iMzdlLTQ1M2QtODA0ZC1hODA5YmE0MmFiMWMiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYnJ6MWhoM0NSWTRwZWp0UkNaODFDWmo4UEVSVzVadFgyTXhTRWV2ekZ4OGtuTllneFptNGVteUJ4WjhweUIyRmlwRzhjaVJWbldRZXVSdTdvSnFmcGtvUWpxaHNBenc1aDh1NVJQRzZYRVpTYXJjYWZNUXVtVXJHdEpjM3R3UVJjOUoiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTcyNDQ0NDAzMiwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlIzgxYjhhN2Q0LWIzN2UtNDUzZC04MDRkLWE4MDliYTQyYWIxYyIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldENyb3NzUHJlQXV0aG9yaXNlZERlZmVycmVkIl0sImlzc3VlciI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEIiwiaXNzdWFuY2VEYXRlIjoiMjAyNC0wOC0yM1QyMDoxMzo1MloiLCJpc3N1ZWQiOiIyMDI0LTA4LTIzVDIwOjEzOjUyWiIsInZhbGlkRnJvbSI6IjIwMjQtMDgtMjNUMjA6MTM6NTJaIiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA4LTI0VDIwOjEzOjU3WiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImlkIjoiZGlkOmtleTp6MmRtekQ4MWNnUHg4VmtpN0pidXVNbUZZcldQZ1lveXR5a1VaM2V5cWh0MWo5S2JyejFoaDNDUlk0cGVqdFJDWjgxQ1pqOFBFUlc1WnRYMk14U0VldnpGeDhrbk5ZZ3habTRlbXlCeFo4cHlCMkZpcEc4Y2lSVm5XUWV1UnU3b0pxZnBrb1FqcWhzQXp3NWg4dTVSUEc2WEVaU2FyY2FmTVF1bVVyR3RKYzN0d1FSYzlKIn0sImNyZWRlbnRpYWxTY2hlbWEiOnsiaWQiOiJodHRwczovL2FwaS1jb25mb3JtYW5jZS5lYnNpLmV1L3RydXN0ZWQtc2NoZW1hcy1yZWdpc3RyeS92My9zY2hlbWFzL3ozTWdVRlVrYjcyMnVxNHgzZHY1eUFKbW5ObXpERmVLNVVDOHg4M1FvZUxKTSIsInR5cGUiOiJGdWxsSnNvblNjaGVtYVZhbGlkYXRvcjIwMjEifSwidGVybXNPZlVzZSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1pc3N1ZXJzLXJlZ2lzdHJ5L3Y1L2lzc3VlcnMvZGlkOmVic2k6empIWmpKNFN5N3I5MkJ4WHpGR3M3cUQvYXR0cmlidXRlcy9iY2RiNmJjOTUyYzhjODk3Y2ExZTYwNWZjZTI1ZjgyNjA0Yzc2YzE2ZDQ3OTc3MDAxNGI3YjI2MmI5M2MwMjUwIiwidHlwZSI6Iklzc3VhbmNlQ2VydGlmaWNhdGUifX19.4hf8Y0RgbO4ayYgtjwEzCc_F0iT0U7zQizpuFy1Vs-pI8CGaWsuqEK6ivnHT5uVCE7vR2uRuYu2wfjBsKJKf3A"
        }
    });
    var vc = resolver.Resolve(q, publicKey, privateKey, CancellationToken.None).Result;

}

string GenerateDidKey()
{
    var exportResult = DidKeyGenerator.New().GenerateRandomES256Key().Export(false, true);
    var export = SignatureKeySerializer.Serialize(exportResult.Key);
    File.WriteAllText(Path.Combine(Directory.GetCurrentDirectory(), "privatekey.json"), JsonSerializer.Serialize(export));
    return exportResult.Did;
}