//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIdServer.IdServer.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleIdServer.IdServer.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à access has been revoked by the resource owner.
        /// </summary>
        public static string AccessRevokedByResourceOwner {
            get {
                return ResourceManager.GetString("AccessRevokedByResourceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the authentication method {0} doesn&apos;t exist.
        /// </summary>
        public static string AuthenticationMethodNotFound {
            get {
                return ResourceManager.GetString("AuthenticationMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à access token is not correct.
        /// </summary>
        public static string BadAccessToken {
            get {
                return ResourceManager.GetString("BadAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad authorization code.
        /// </summary>
        public static string BadAuthorizationCode {
            get {
                return ResourceManager.GetString("BadAuthorizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à claim_token parameter is not a JWS token.
        /// </summary>
        public static string BadClaimToken {
            get {
                return ResourceManager.GetString("BadClaimToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the algorithm used by client assertion is not correct.
        /// </summary>
        public static string BadClientAssertionAlg {
            get {
                return ResourceManager.GetString("BadClientAssertionAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad client assertion audiences.
        /// </summary>
        public static string BadClientAssertionAudiences {
            get {
                return ResourceManager.GetString("BadClientAssertionAudiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad client assertion decryption.
        /// </summary>
        public static string BadClientAssertionDecryption {
            get {
                return ResourceManager.GetString("BadClientAssertionDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à client_assertion cannot be encrypted (JWE).
        /// </summary>
        public static string BadClientAssertionEncrypted {
            get {
                return ResourceManager.GetString("BadClientAssertionEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à client assertion is expired.
        /// </summary>
        public static string BadClientAssertionExpired {
            get {
                return ResourceManager.GetString("BadClientAssertionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad client assertion format.
        /// </summary>
        public static string BadClientAssertionFormat {
            get {
                return ResourceManager.GetString("BadClientAssertionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad client assertion issuer.
        /// </summary>
        public static string BadClientAssertionIssuer {
            get {
                return ResourceManager.GetString("BadClientAssertionIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à client_assertion is not a valid JWT token.
        /// </summary>
        public static string BadClientAssertionJwt {
            get {
                return ResourceManager.GetString("BadClientAssertionJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad client assertion signature.
        /// </summary>
        public static string BadClientAssertionSignature {
            get {
                return ResourceManager.GetString("BadClientAssertionSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad client credential.
        /// </summary>
        public static string BadClientCredential {
            get {
                return ResourceManager.GetString("BadClientCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à grant type {0} is not supported by the client.
        /// </summary>
        public static string BadClientGrantType {
            get {
                return ResourceManager.GetString("BadClientGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à client uri {0} is not correct.
        /// </summary>
        public static string BadClientUri {
            get {
                return ResourceManager.GetString("BadClientUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à transform algorithm {0} is not supported.
        /// </summary>
        public static string BadCodeChallengeMethod {
            get {
                return ResourceManager.GetString("BadCodeChallengeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à code_verifier is invalid.
        /// </summary>
        public static string BadCodeVerifier {
            get {
                return ResourceManager.GetString("BadCodeVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à an error occured while trying to authenticate the user.
        /// </summary>
        public static string BadExternalAuthentication {
            get {
                return ResourceManager.GetString("BadExternalAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no identifier can be extracted from the external authentication provider.
        /// </summary>
        public static string BadExternalAuthenticationUser {
            get {
                return ResourceManager.GetString("BadExternalAuthenticationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad grant type.
        /// </summary>
        public static string BadGrantType {
            get {
                return ResourceManager.GetString("BadGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à signature of the id_token_hint is not correct.
        /// </summary>
        public static string BadIdTokenHintSig {
            get {
                return ResourceManager.GetString("BadIdTokenHintSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à software statement issuer is not trusted.
        /// </summary>
        public static string BadIssuerSoftwareStatement {
            get {
                return ResourceManager.GetString("BadIssuerSoftwareStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jwks uri {0} is not correct.
        /// </summary>
        public static string BadJwksUri {
            get {
                return ResourceManager.GetString("BadJwksUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à software statement is not a JWS token.
        /// </summary>
        public static string BadJwsSoftwareStatement {
            get {
                return ResourceManager.GetString("BadJwsSoftwareStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à logo uri {0} is not correct.
        /// </summary>
        public static string BadLogoUri {
            get {
                return ResourceManager.GetString("BadLogoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à policy uri {0} is not correct.
        /// </summary>
        public static string BadPolicyUri {
            get {
                return ResourceManager.GetString("BadPolicyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à redirect_uri {0} is not correct.
        /// </summary>
        public static string BadRedirectUri {
            get {
                return ResourceManager.GetString("BadRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad refresh token.
        /// </summary>
        public static string BadRefreshToken {
            get {
                return ResourceManager.GetString("BadRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à response mode {0} is not supported.
        /// </summary>
        public static string BadResponseMode {
            get {
                return ResourceManager.GetString("BadResponseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à response type must equals to &apos;code&apos;.
        /// </summary>
        public static string BadResponseType {
            get {
                return ResourceManager.GetString("BadResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à response types {0} are not supported.
        /// </summary>
        public static string BadResponseTypes {
            get {
                return ResourceManager.GetString("BadResponseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à response types {0} are not supported by the client.
        /// </summary>
        public static string BadResponseTypesClient {
            get {
                return ResourceManager.GetString("BadResponseTypesClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the certificate is not correct.
        /// </summary>
        public static string BadSelfSignedCertificate {
            get {
                return ResourceManager.GetString("BadSelfSignedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à software statement signature is invalid.
        /// </summary>
        public static string BadSoftwareStatementSignature {
            get {
                return ResourceManager.GetString("BadSoftwareStatementSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad token.
        /// </summary>
        public static string BadToken {
            get {
                return ResourceManager.GetString("BadToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à token format {0} is invalid.
        /// </summary>
        public static string BadTokenFormat {
            get {
                return ResourceManager.GetString("BadTokenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tos uri {0} is not correct.
        /// </summary>
        public static string BadTosUri {
            get {
                return ResourceManager.GetString("BadTosUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bad user credential.
        /// </summary>
        public static string BadUserCredential {
            get {
                return ResourceManager.GetString("BadUserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à binding_message must not exceed {0} characters.
        /// </summary>
        public static string BindingMessageMustNotExceed {
            get {
                return ResourceManager.GetString("BindingMessageMustNotExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à duplicate scopes : {0}.
        /// </summary>
        public static string DuplicateScopes {
            get {
                return ResourceManager.GetString("DuplicateScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à access token has an invalid scope.
        /// </summary>
        public static string InvalidAccessTokenScope {
            get {
                return ResourceManager.GetString("InvalidAccessTokenScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the alg used to sign the id_token_hint is invalid.
        /// </summary>
        public static string InvalidAlgUsedToSignIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidAlgUsedToSignIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à application type is invalid.
        /// </summary>
        public static string InvalidApplicationType {
            get {
                return ResourceManager.GetString("InvalidApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à invalid audiences.
        /// </summary>
        public static string InvalidAudience {
            get {
                return ResourceManager.GetString("InvalidAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à audience contained in id_token_hint is invalid.
        /// </summary>
        public static string InvalidAudienceIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidAudienceIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the authorization_details location must be equal to the authorization server {0}.
        /// </summary>
        public static string InvalidAuthDetailsLocation {
            get {
                return ResourceManager.GetString("InvalidAuthDetailsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the status of the authentication device is invalid, it must be equals to PENDING.
        /// </summary>
        public static string InvalidAuthDeviceStatusForRejection {
            get {
                return ResourceManager.GetString("InvalidAuthDeviceStatusForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à authorization request doesn&apos;t exist.
        /// </summary>
        public static string InvalidAuthRequestId {
            get {
                return ResourceManager.GetString("InvalidAuthRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à invalid back channel client notification endpoint.
        /// </summary>
        public static string InvalidBcClientNotificationEdp {
            get {
                return ResourceManager.GetString("InvalidBcClientNotificationEdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à invalid back channel delivery mode.
        /// </summary>
        public static string InvalidBcDeliveryMode {
            get {
                return ResourceManager.GetString("InvalidBcDeliveryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à claims {0} are invalid.
        /// </summary>
        public static string InvalidClaims {
            get {
                return ResourceManager.GetString("InvalidClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the client_id claim is invalid.
        /// </summary>
        public static string InvalidClientIdClaim {
            get {
                return ResourceManager.GetString("InvalidClientIdClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the device code has not been issued for this client.
        /// </summary>
        public static string InvalidClientIdDeviceCode {
            get {
                return ResourceManager.GetString("InvalidClientIdDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à client_id contained in the id_token_hint is invalid.
        /// </summary>
        public static string InvalidClientIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidClientIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DPoP must be bound to the access token.
        /// </summary>
        public static string InvalidDpopBoundToAccessToken {
            get {
                return ResourceManager.GetString("InvalidDpopBoundToAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the DPoP parameter must be a string.
        /// </summary>
        public static string InvalidDpopHeader {
            get {
                return ResourceManager.GetString("InvalidDpopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the alg / enc used to encrypt the id_token_hint is invalid.
        /// </summary>
        public static string InvalidEncOrAlgUsedToEncryptIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidEncOrAlgUsedToEncryptIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the device code is expired.
        /// </summary>
        public static string InvalidExpiredDeviceCode {
            get {
                return ResourceManager.GetString("InvalidExpiredDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the grant_management_action {0} is not valid.
        /// </summary>
        public static string InvalidGrantManagementAction {
            get {
                return ResourceManager.GetString("InvalidGrantManagementAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à client notification endpoint doesn&apos;t contain https scheme.
        /// </summary>
        public static string InvalidHttpsBcClientNotificationEdp {
            get {
                return ResourceManager.GetString("InvalidHttpsBcClientNotificationEdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à initiate_login_uri doesn&apos;t contain https scheme.
        /// </summary>
        public static string InvalidHttpsInitiateLoginUri {
            get {
                return ResourceManager.GetString("InvalidHttpsInitiateLoginUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à redirect_uri does not contain https scheme.
        /// </summary>
        public static string InvalidHttpsRedirectUri {
            get {
                return ResourceManager.GetString("InvalidHttpsRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sector_identifier_uri doesn&apos;t contain https scheme.
        /// </summary>
        public static string InvalidHttpsSectorIdentifierUri {
            get {
                return ResourceManager.GetString("InvalidHttpsSectorIdentifierUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_token_hint is invalid.
        /// </summary>
        public static string InvalidIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à incoming request is invalid.
        /// </summary>
        public static string InvalidIncomingRequest {
            get {
                return ResourceManager.GetString("InvalidIncomingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à initiate_login_uri is not a valid URI.
        /// </summary>
        public static string InvalidInitiateLoginUri {
            get {
                return ResourceManager.GetString("InvalidInitiateLoginUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the device code has already been used to get a token.
        /// </summary>
        public static string InvalidIssuedDeviceCode {
            get {
                return ResourceManager.GetString("InvalidIssuedDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à request parameter is not a valid JWE token.
        /// </summary>
        public static string InvalidJweRequestParameter {
            get {
                return ResourceManager.GetString("InvalidJweRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à request parameter is not a valid JWS token.
        /// </summary>
        public static string InvalidJwsRequestParameter {
            get {
                return ResourceManager.GetString("InvalidJwsRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON Web Token cannot be read.
        /// </summary>
        public static string InvalidJwt {
            get {
                return ResourceManager.GetString("InvalidJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à redirect_uri must not contain localhost.
        /// </summary>
        public static string InvalidLocahostRedirectUri {
            get {
                return ResourceManager.GetString("InvalidLocahostRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à authorization request is still pending as the end user hasn&apos;t yet completed the user-interation steps.
        /// </summary>
        public static string InvalidPendingDeviceCode {
            get {
                return ResourceManager.GetString("InvalidPendingDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the pin is invalid.
        /// </summary>
        public static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à post_logout_redirect_uri parameter is invalid.
        /// </summary>
        public static string InvalidPostLogoutRedirectUrl {
            get {
                return ResourceManager.GetString("InvalidPostLogoutRedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à either the pre-authorized code has expired or is invalid.
        /// </summary>
        public static string InvalidPreAuthorizedCode {
            get {
                return ResourceManager.GetString("InvalidPreAuthorizedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à request parameter is invalid.
        /// </summary>
        public static string InvalidRequestParameter {
            get {
                return ResourceManager.GetString("InvalidRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à request_uri parameter is invalid.
        /// </summary>
        public static string InvalidRequestUriParameter {
            get {
                return ResourceManager.GetString("InvalidRequestUriParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one of the provided resource identifiers was not found at the authorization server..
        /// </summary>
        public static string InvalidResourceId {
            get {
                return ResourceManager.GetString("InvalidResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the response_type claim is invalid.
        /// </summary>
        public static string InvalidResponseTypeClaim {
            get {
                return ResourceManager.GetString("InvalidResponseTypeClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one of the scopes included in the request does not match an available scope for any of the resources associated with requested permissions for the permission ticket provided by the client..
        /// </summary>
        public static string InvalidScope {
            get {
                return ResourceManager.GetString("InvalidScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sector_identifier_uri is not a valid URI.
        /// </summary>
        public static string InvalidSectorIdentifierUri {
            get {
                return ResourceManager.GetString("InvalidSectorIdentifierUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the signature algorithm is invalid.
        /// </summary>
        public static string InvalidSignatureAlg {
            get {
                return ResourceManager.GetString("InvalidSignatureAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à subject contained in id_token_hint is invalid.
        /// </summary>
        public static string InvalidSubjectIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidSubjectIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string InvalidSubjectType {
            get {
                return ResourceManager.GetString("InvalidSubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à permission ticket is not correct.
        /// </summary>
        public static string InvalidTicket {
            get {
                return ResourceManager.GetString("InvalidTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the tx_code is invalid.
        /// </summary>
        public static string InvalidTransactionCode {
            get {
                return ResourceManager.GetString("InvalidTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one of the scopes included in the request does not match an available scope for any of the resources associated with requested permissions for the permission ticket provided by the client..
        /// </summary>
        public static string InvalidUmaPermissionScope {
            get {
                return ResourceManager.GetString("InvalidUmaPermissionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one of the scopes included in the request does not match an available scope for any of the resources associated with requested permissions for the permission ticket provided by the client..
        /// </summary>
        public static string InvalidUmaResource {
            get {
                return ResourceManager.GetString("InvalidUmaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the user_code is not valid.
        /// </summary>
        public static string InvalidUserCode {
            get {
                return ResourceManager.GetString("InvalidUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no client secret.
        /// </summary>
        public static string NoClientSecret {
            get {
                return ResourceManager.GetString("NoClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no consent has been accepted.
        /// </summary>
        public static string NoConsent {
            get {
                return ResourceManager.GetString("NoConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no JWK with identifier {0} has been found to check the signature of the JWT.
        /// </summary>
        public static string NoJwkFoundToCheckSig {
            get {
                return ResourceManager.GetString("NoJwkFoundToCheckSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no JWK with identifier {0} has been found to decrypt the JWT.
        /// </summary>
        public static string NoJwkFoundToDecrypt {
            get {
                return ResourceManager.GetString("NoJwkFoundToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no JWK with algorithm {0} has been found to sign the JWT.
        /// </summary>
        public static string NoJwkWithAlgSig {
            get {
                return ResourceManager.GetString("NoJwkWithAlgSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the incoming request doesn&apos;t contain a session_id.
        /// </summary>
        public static string NoSessionId {
            get {
                return ResourceManager.GetString("NoSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à you&apos;re not authorized to access to the permissions endpoint.
        /// </summary>
        public static string UnauthorizedAccessPermissionApi {
            get {
                return ResourceManager.GetString("UnauthorizedAccessPermissionApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the access token is not authorized to access to the operation.
        /// </summary>
        public static string UnauthorizedAccessToken {
            get {
                return ResourceManager.GetString("UnauthorizedAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unauthorized client.
        /// </summary>
        public static string UnauthorizedClient {
            get {
                return ResourceManager.GetString("UnauthorizedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the client {0} is not authorized to access to perform operations on the grant.
        /// </summary>
        public static string UnauthorizedClientAccessGrant {
            get {
                return ResourceManager.GetString("UnauthorizedClientAccessGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unauthorized to scopes : {0}.
        /// </summary>
        public static string UnauthorizedScopes {
            get {
                return ResourceManager.GetString("UnauthorizedScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the user {0} is not authorized to access to performance operations on the grant.
        /// </summary>
        public static string UnauthorizedUserAccessGrant {
            get {
                return ResourceManager.GetString("UnauthorizedUserAccessGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à either the access token has been revoked or is invalid.
        /// </summary>
        public static string UnknownAccessToken {
            get {
                return ResourceManager.GetString("UnknownAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the acr {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownAcr {
            get {
                return ResourceManager.GetString("UnknownAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the API resource {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownApiResource {
            get {
                return ResourceManager.GetString("UnknownApiResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à following audiences {0} don&apos;t exist.
        /// </summary>
        public static string UnknownAudience {
            get {
                return ResourceManager.GetString("UnknownAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown authentication method : {0}.
        /// </summary>
        public static string UnknownAuthMethod {
            get {
                return ResourceManager.GetString("UnknownAuthMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the authentication methods {0} are unknown.
        /// </summary>
        public static string UnknownAuthMethods {
            get {
                return ResourceManager.GetString("UnknownAuthMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the authentication scheme provider {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownAuthSchemeProvider {
            get {
                return ResourceManager.GetString("UnknownAuthSchemeProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the authentication scheme provider cannot be updated because the following properties are unknown : {0}.
        /// </summary>
        public static string UnknownAuthSchemeProviderProperties {
            get {
                return ResourceManager.GetString("UnknownAuthSchemeProviderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the back channel authorization {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownBcAuthorize {
            get {
                return ResourceManager.GetString("UnknownBcAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown certificate authority {0}.
        /// </summary>
        public static string UnknownCa {
            get {
                return ResourceManager.GetString("UnknownCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown client {0}.
        /// </summary>
        public static string UnknownClient {
            get {
                return ResourceManager.GetString("UnknownClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown client certificate {0}.
        /// </summary>
        public static string UnknownClientCa {
            get {
                return ResourceManager.GetString("UnknownClientCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the credential offer doesn&apos;t exist.
        /// </summary>
        public static string UnknownCredentialOffer {
            get {
                return ResourceManager.GetString("UnknownCredentialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the device_code doesn&apos;t exist.
        /// </summary>
        public static string UnknownDeviceCode {
            get {
                return ResourceManager.GetString("UnknownDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the device {0} is not supported.
        /// </summary>
        public static string UnknownDeviceType {
            get {
                return ResourceManager.GetString("UnknownDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the grant {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownGrant {
            get {
                return ResourceManager.GetString("UnknownGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the group {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownGroup {
            get {
                return ResourceManager.GetString("UnknownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the group {0} don&apos;t exist.
        /// </summary>
        public static string UnknownGroupIds {
            get {
                return ResourceManager.GetString("UnknownGroupIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown role {0}.
        /// </summary>
        public static string UnknownGroupRole {
            get {
                return ResourceManager.GetString("UnknownGroupRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the identity provisioning {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownIdProvisioning {
            get {
                return ResourceManager.GetString("UnknownIdProvisioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the mapping rule {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownIdProvisioningMappingRule {
            get {
                return ResourceManager.GetString("UnknownIdProvisioningMappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the process {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownIdProvisioningProcess {
            get {
                return ResourceManager.GetString("UnknownIdProvisioningProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Json Web Key doesn&apos;t exist.
        /// </summary>
        public static string UnknownJsonWebKey {
            get {
                return ResourceManager.GetString("UnknownJsonWebKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the permissions {0} don&apos;t exist.
        /// </summary>
        public static string UnknownPermissions {
            get {
                return ResourceManager.GetString("UnknownPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no registration workflow has been resolved.
        /// </summary>
        public static string UnknownRegistrationWorkflow {
            get {
                return ResourceManager.GetString("UnknownRegistrationWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à following resources {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownResource {
            get {
                return ResourceManager.GetString("UnknownResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown scope {0}.
        /// </summary>
        public static string UnknownScope {
            get {
                return ResourceManager.GetString("UnknownScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown scope claim mapper {0}.
        /// </summary>
        public static string UnknownScopeClaimMapper {
            get {
                return ResourceManager.GetString("UnknownScopeClaimMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à scopes {0} are not present in the resource / audience.
        /// </summary>
        public static string UnknownScopeResourceOrAudience {
            get {
                return ResourceManager.GetString("UnknownScopeResourceOrAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown token type hint : {0}.
        /// </summary>
        public static string UnknownTokenTypeHint {
            get {
                return ResourceManager.GetString("UnknownTokenTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the UMA resource doesn&apos;t exist.
        /// </summary>
        public static string UnknownUmaResource {
            get {
                return ResourceManager.GetString("UnknownUmaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown user {0}.
        /// </summary>
        public static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown user&apos;s consent {0}.
        /// </summary>
        public static string UnknownUserConsent {
            get {
                return ResourceManager.GetString("UnknownUserConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown user&apos;s credential {0}.
        /// </summary>
        public static string UnknownUserCredential {
            get {
                return ResourceManager.GetString("UnknownUserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown user&apos;s external authentication provider.
        /// </summary>
        public static string UnknownUserExternalAuthProvider {
            get {
                return ResourceManager.GetString("UnknownUserExternalAuthProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown user&apos;s group {0}.
        /// </summary>
        public static string UnknownUserGroup {
            get {
                return ResourceManager.GetString("UnknownUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown user&apos;s session {0}.
        /// </summary>
        public static string UnknownUserSession {
            get {
                return ResourceManager.GetString("UnknownUserSession", resourceCulture);
            }
        }
    }
}
