//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIdServer.IdServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleIdServer.IdServer.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access has been revoked by the resource owner.
        /// </summary>
        public static string AccessRevokedByResourceOwner {
            get {
                return ResourceManager.GetString("AccessRevokedByResourceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access token has been rejected.
        /// </summary>
        public static string AccessTokenRejected {
            get {
                return ResourceManager.GetString("AccessTokenRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access token can be used for the client &apos;{0}&apos; and not for &apos;{1}&apos;.
        /// </summary>
        public static string AccessTokenValidClient {
            get {
                return ResourceManager.GetString("AccessTokenValidClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authentication method {0} doesn&apos;t exist.
        /// </summary>
        public static string AuthenticationMethodNotFound {
            get {
                return ResourceManager.GetString("AuthenticationMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization code has already been used, all tokens previously issued have been revoked.
        /// </summary>
        public static string AuthorizationCodeAlreadyUsed {
            get {
                return ResourceManager.GetString("AuthorizationCodeAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization code has not been issued by the client.
        /// </summary>
        public static string AuthorizationCodeNotIssuedByClient {
            get {
                return ResourceManager.GetString("AuthorizationCodeNotIssuedByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access token is not correct.
        /// </summary>
        public static string BadAccessToken {
            get {
                return ResourceManager.GetString("BadAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad authorization code.
        /// </summary>
        public static string BadAuthorizationCode {
            get {
                return ResourceManager.GetString("BadAuthorizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to claim_token parameter is not a JWS token.
        /// </summary>
        public static string BadClaimToken {
            get {
                return ResourceManager.GetString("BadClaimToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the algorithm used by client assertion is not correct.
        /// </summary>
        public static string BadClientAssertionAlg {
            get {
                return ResourceManager.GetString("BadClientAssertionAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad client assertion audiences.
        /// </summary>
        public static string BadClientAssertionAudiences {
            get {
                return ResourceManager.GetString("BadClientAssertionAudiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad client assertion decryption.
        /// </summary>
        public static string BadClientAssertionDecryption {
            get {
                return ResourceManager.GetString("BadClientAssertionDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_assertion cannot be encrypted (JWE).
        /// </summary>
        public static string BadClientAssertionEncrypted {
            get {
                return ResourceManager.GetString("BadClientAssertionEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion is expired.
        /// </summary>
        public static string BadClientAssertionExpired {
            get {
                return ResourceManager.GetString("BadClientAssertionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad client assertion format.
        /// </summary>
        public static string BadClientAssertionFormat {
            get {
                return ResourceManager.GetString("BadClientAssertionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad client assertion issuer.
        /// </summary>
        public static string BadClientAssertionIssuer {
            get {
                return ResourceManager.GetString("BadClientAssertionIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_assertion is not a valid JWT token.
        /// </summary>
        public static string BadClientAssertionJwt {
            get {
                return ResourceManager.GetString("BadClientAssertionJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad client assertion signature.
        /// </summary>
        public static string BadClientAssertionSignature {
            get {
                return ResourceManager.GetString("BadClientAssertionSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad client credential.
        /// </summary>
        public static string BadClientCredential {
            get {
                return ResourceManager.GetString("BadClientCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant type {0} is not supported by the client.
        /// </summary>
        public static string BadClientGrantType {
            get {
                return ResourceManager.GetString("BadClientGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client uri {0} is not correct.
        /// </summary>
        public static string BadClientUri {
            get {
                return ResourceManager.GetString("BadClientUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transform algorithm {0} is not supported.
        /// </summary>
        public static string BadCodeChallengeMethod {
            get {
                return ResourceManager.GetString("BadCodeChallengeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code_verifier is invalid.
        /// </summary>
        public static string BadCodeVerifier {
            get {
                return ResourceManager.GetString("BadCodeVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error occured while trying to authenticate the user.
        /// </summary>
        public static string BadExternalAuthentication {
            get {
                return ResourceManager.GetString("BadExternalAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no identifier can be extracted from the external authentication provider.
        /// </summary>
        public static string BadExternalAuthenticationUser {
            get {
                return ResourceManager.GetString("BadExternalAuthenticationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad grant type.
        /// </summary>
        public static string BadGrantType {
            get {
                return ResourceManager.GetString("BadGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signature of the id_token_hint is not correct.
        /// </summary>
        public static string BadIdTokenHintSig {
            get {
                return ResourceManager.GetString("BadIdTokenHintSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software statement issuer is not trusted.
        /// </summary>
        public static string BadIssuerSoftwareStatement {
            get {
                return ResourceManager.GetString("BadIssuerSoftwareStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jwks uri {0} is not correct.
        /// </summary>
        public static string BadJwksUri {
            get {
                return ResourceManager.GetString("BadJwksUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software statement is not a JWS token.
        /// </summary>
        public static string BadJwsSoftwareStatement {
            get {
                return ResourceManager.GetString("BadJwsSoftwareStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo uri {0} is not correct.
        /// </summary>
        public static string BadLogoUri {
            get {
                return ResourceManager.GetString("BadLogoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to policy uri {0} is not correct.
        /// </summary>
        public static string BadPolicyUri {
            get {
                return ResourceManager.GetString("BadPolicyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirect_uri {0} is not correct.
        /// </summary>
        public static string BadRedirectUri {
            get {
                return ResourceManager.GetString("BadRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad refresh token.
        /// </summary>
        public static string BadRefreshToken {
            get {
                return ResourceManager.GetString("BadRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response mode {0} is not supported.
        /// </summary>
        public static string BadResponseMode {
            get {
                return ResourceManager.GetString("BadResponseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response type must equals to &apos;code&apos;.
        /// </summary>
        public static string BadResponseType {
            get {
                return ResourceManager.GetString("BadResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response types {0} are not supported.
        /// </summary>
        public static string BadResponseTypes {
            get {
                return ResourceManager.GetString("BadResponseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response types {0} are not supported by the client.
        /// </summary>
        public static string BadResponseTypesClient {
            get {
                return ResourceManager.GetString("BadResponseTypesClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the certificate is not correct.
        /// </summary>
        public static string BadSelfSignedCertificate {
            get {
                return ResourceManager.GetString("BadSelfSignedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software statement signature is invalid.
        /// </summary>
        public static string BadSoftwareStatementSignature {
            get {
                return ResourceManager.GetString("BadSoftwareStatementSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad token.
        /// </summary>
        public static string BadToken {
            get {
                return ResourceManager.GetString("BadToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token format {0} is invalid.
        /// </summary>
        public static string BadTokenFormat {
            get {
                return ResourceManager.GetString("BadTokenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tos uri {0} is not correct.
        /// </summary>
        public static string BadTosUri {
            get {
                return ResourceManager.GetString("BadTosUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad user credential.
        /// </summary>
        public static string BadUserCredential {
            get {
                return ResourceManager.GetString("BadUserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binding_message must not exceed {0} characters.
        /// </summary>
        public static string BindingMessageMustNotExceed {
            get {
                return ResourceManager.GetString("BindingMessageMustNotExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion cannot be decryted by the client secret.
        /// </summary>
        public static string ClientAssertionCannotBeDecrypted {
            get {
                return ResourceManager.GetString("ClientAssertionCannotBeDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion is missing.
        /// </summary>
        public static string ClientAssertionIsMissing {
            get {
                return ResourceManager.GetString("ClientAssertionIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion must be encrypted JWT (JWE).
        /// </summary>
        public static string ClientAssertionIsNotEncrypted {
            get {
                return ResourceManager.GetString("ClientAssertionIsNotEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion must be a signed JWT (JWS).
        /// </summary>
        public static string ClientAssertionIsNotSigned {
            get {
                return ResourceManager.GetString("ClientAssertionIsNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion must be encrypted JWT (JWE).
        /// </summary>
        public static string ClientAssertionMustBeEncrypted {
            get {
                return ResourceManager.GetString("ClientAssertionMustBeEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion is not signed by a known Json Web Key.
        /// </summary>
        public static string ClientAssertionNotSignedByKnownJwk {
            get {
                return ResourceManager.GetString("ClientAssertionNotSignedByKnownJwk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected client_assertion_type, must be equals to {0}.
        /// </summary>
        public static string ClientAssertionTypeIsUnexpected {
            get {
                return ResourceManager.GetString("ClientAssertionTypeIsUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client assertion type {0} is not supported.
        /// </summary>
        public static string ClientAssertionTypeNotSupported {
            get {
                return ResourceManager.GetString("ClientAssertionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_id cannot be extracted from client_assertion.
        /// </summary>
        public static string ClientIdCannotBeExtractedFromClientAssertion {
            get {
                return ResourceManager.GetString("ClientIdCannotBeExtractedFromClientAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client identifier {0} already exists.
        /// </summary>
        public static string ClientIdentifierAlreadyExists {
            get {
                return ResourceManager.GetString("ClientIdentifierAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client identifier must be identical.
        /// </summary>
        public static string ClientIdentifierMustBeIdentical {
            get {
                return ResourceManager.GetString("ClientIdentifierMustBeIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_notification_token must not exceed 1024 characters.
        /// </summary>
        public static string ClientNotificationTokenCannotExceed1024 {
            get {
                return ResourceManager.GetString("ClientNotificationTokenCannotExceed1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_notification_token must contains at least 128 bytes.
        /// </summary>
        public static string ClientNotificationTokenMustContainsAtLeast128Bytes {
            get {
                return ResourceManager.GetString("ClientNotificationTokenMustContainsAtLeast128Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client secret must be identical.
        /// </summary>
        public static string ClientSecretMustBeIdentical {
            get {
                return ResourceManager.GetString("ClientSecretMustBeIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token exchange is not enabled.
        /// </summary>
        public static string ClientTokenExchangedNotEnabled {
            get {
                return ResourceManager.GetString("ClientTokenExchangedNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jwks and jwks_uri parameters cannot be passed at the same time.
        /// </summary>
        public static string DuplicateJwks {
            get {
                return ResourceManager.GetString("DuplicateJwks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate scopes : {0}.
        /// </summary>
        public static string DuplicateScopes {
            get {
                return ResourceManager.GetString("DuplicateScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access token has an invalid scope.
        /// </summary>
        public static string InvalidAccessTokenScope {
            get {
                return ResourceManager.GetString("InvalidAccessTokenScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the alg used to sign the id_token_hint is invalid.
        /// </summary>
        public static string InvalidAlgUsedToSignIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidAlgUsedToSignIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application type is invalid.
        /// </summary>
        public static string InvalidApplicationType {
            get {
                return ResourceManager.GetString("InvalidApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid audiences.
        /// </summary>
        public static string InvalidAudience {
            get {
                return ResourceManager.GetString("InvalidAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audience contained in id_token_hint is invalid.
        /// </summary>
        public static string InvalidAudienceIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidAudienceIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authorization_details location must be equal to the authorization server {0}.
        /// </summary>
        public static string InvalidAuthDetailsLocation {
            get {
                return ResourceManager.GetString("InvalidAuthDetailsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the status of the authentication device is invalid, it must be equals to PENDING.
        /// </summary>
        public static string InvalidAuthDeviceStatusForRejection {
            get {
                return ResourceManager.GetString("InvalidAuthDeviceStatusForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization request doesn&apos;t exist.
        /// </summary>
        public static string InvalidAuthRequestId {
            get {
                return ResourceManager.GetString("InvalidAuthRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid back channel client notification endpoint.
        /// </summary>
        public static string InvalidBcClientNotificationEdp {
            get {
                return ResourceManager.GetString("InvalidBcClientNotificationEdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid back channel delivery mode.
        /// </summary>
        public static string InvalidBcDeliveryMode {
            get {
                return ResourceManager.GetString("InvalidBcDeliveryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to claims {0} are invalid.
        /// </summary>
        public static string InvalidClaims {
            get {
                return ResourceManager.GetString("InvalidClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client_id claim is invalid.
        /// </summary>
        public static string InvalidClientIdClaim {
            get {
                return ResourceManager.GetString("InvalidClientIdClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the device code has not been issued for this client.
        /// </summary>
        public static string InvalidClientIdDeviceCode {
            get {
                return ResourceManager.GetString("InvalidClientIdDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_id contained in the id_token_hint is invalid.
        /// </summary>
        public static string InvalidClientIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidClientIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPoP must be bound to the access token.
        /// </summary>
        public static string InvalidDpopBoundToAccessToken {
            get {
                return ResourceManager.GetString("InvalidDpopBoundToAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DPoP parameter must be a string.
        /// </summary>
        public static string InvalidDpopHeader {
            get {
                return ResourceManager.GetString("InvalidDpopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the alg / enc used to encrypt the id_token_hint is invalid.
        /// </summary>
        public static string InvalidEncOrAlgUsedToEncryptIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidEncOrAlgUsedToEncryptIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the device code is expired.
        /// </summary>
        public static string InvalidExpiredDeviceCode {
            get {
                return ResourceManager.GetString("InvalidExpiredDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the grant_management_action {0} is not valid.
        /// </summary>
        public static string InvalidGrantManagementAction {
            get {
                return ResourceManager.GetString("InvalidGrantManagementAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client notification endpoint doesn&apos;t contain https scheme.
        /// </summary>
        public static string InvalidHttpsBcClientNotificationEdp {
            get {
                return ResourceManager.GetString("InvalidHttpsBcClientNotificationEdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initiate_login_uri doesn&apos;t contain https scheme.
        /// </summary>
        public static string InvalidHttpsInitiateLoginUri {
            get {
                return ResourceManager.GetString("InvalidHttpsInitiateLoginUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirect_uri does not contain https scheme.
        /// </summary>
        public static string InvalidHttpsRedirectUri {
            get {
                return ResourceManager.GetString("InvalidHttpsRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sector_identifier_uri doesn&apos;t contain https scheme.
        /// </summary>
        public static string InvalidHttpsSectorIdentifierUri {
            get {
                return ResourceManager.GetString("InvalidHttpsSectorIdentifierUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_token_hint is invalid.
        /// </summary>
        public static string InvalidIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incoming request is invalid.
        /// </summary>
        public static string InvalidIncomingRequest {
            get {
                return ResourceManager.GetString("InvalidIncomingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initiate_login_uri is not a valid URI.
        /// </summary>
        public static string InvalidInitiateLoginUri {
            get {
                return ResourceManager.GetString("InvalidInitiateLoginUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the device code has already been used to get a token.
        /// </summary>
        public static string InvalidIssuedDeviceCode {
            get {
                return ResourceManager.GetString("InvalidIssuedDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request parameter is not a valid JWE token.
        /// </summary>
        public static string InvalidJweRequestParameter {
            get {
                return ResourceManager.GetString("InvalidJweRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request parameter is not a valid JWS token.
        /// </summary>
        public static string InvalidJwsRequestParameter {
            get {
                return ResourceManager.GetString("InvalidJwsRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Web Token cannot be read.
        /// </summary>
        public static string InvalidJwt {
            get {
                return ResourceManager.GetString("InvalidJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirect_uri must not contain localhost.
        /// </summary>
        public static string InvalidLocahostRedirectUri {
            get {
                return ResourceManager.GetString("InvalidLocahostRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization request is still pending as the end user hasn&apos;t yet completed the user-interation steps.
        /// </summary>
        public static string InvalidPendingDeviceCode {
            get {
                return ResourceManager.GetString("InvalidPendingDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the pin is invalid.
        /// </summary>
        public static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post_logout_redirect_uri parameter is invalid.
        /// </summary>
        public static string InvalidPostLogoutRedirectUrl {
            get {
                return ResourceManager.GetString("InvalidPostLogoutRedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to either the pre-authorized code has expired or is invalid.
        /// </summary>
        public static string InvalidPreAuthorizedCode {
            get {
                return ResourceManager.GetString("InvalidPreAuthorizedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request parameter is invalid.
        /// </summary>
        public static string InvalidRequestParameter {
            get {
                return ResourceManager.GetString("InvalidRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request_uri parameter is invalid.
        /// </summary>
        public static string InvalidRequestUriParameter {
            get {
                return ResourceManager.GetString("InvalidRequestUriParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the provided resource identifiers was not found at the authorization server..
        /// </summary>
        public static string InvalidResourceId {
            get {
                return ResourceManager.GetString("InvalidResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the response_type claim is invalid.
        /// </summary>
        public static string InvalidResponseTypeClaim {
            get {
                return ResourceManager.GetString("InvalidResponseTypeClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the scopes included in the request does not match an available scope for any of the resources associated with requested permissions for the permission ticket provided by the client..
        /// </summary>
        public static string InvalidScope {
            get {
                return ResourceManager.GetString("InvalidScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sector_identifier_uri is not a valid URI.
        /// </summary>
        public static string InvalidSectorIdentifierUri {
            get {
                return ResourceManager.GetString("InvalidSectorIdentifierUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the signature algorithm is invalid.
        /// </summary>
        public static string InvalidSignatureAlg {
            get {
                return ResourceManager.GetString("InvalidSignatureAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject contained in id_token_hint is invalid.
        /// </summary>
        public static string InvalidSubjectIdTokenHint {
            get {
                return ResourceManager.GetString("InvalidSubjectIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InvalidSubjectType {
            get {
                return ResourceManager.GetString("InvalidSubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permission ticket is not correct.
        /// </summary>
        public static string InvalidTicket {
            get {
                return ResourceManager.GetString("InvalidTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the tx_code is invalid.
        /// </summary>
        public static string InvalidTransactionCode {
            get {
                return ResourceManager.GetString("InvalidTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the scopes included in the request does not match an available scope for any of the resources associated with requested permissions for the permission ticket provided by the client..
        /// </summary>
        public static string InvalidUmaPermissionScope {
            get {
                return ResourceManager.GetString("InvalidUmaPermissionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the scopes included in the request does not match an available scope for any of the resources associated with requested permissions for the permission ticket provided by the client..
        /// </summary>
        public static string InvalidUmaResource {
            get {
                return ResourceManager.GetString("InvalidUmaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user_code is not valid.
        /// </summary>
        public static string InvalidUserCode {
            get {
                return ResourceManager.GetString("InvalidUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login_hint_token has expired.
        /// </summary>
        public static string LoginHintTokenIsExpired {
            get {
                return ResourceManager.GetString("LoginHintTokenIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login is required.
        /// </summary>
        public static string LoginIsRequired {
            get {
                return ResourceManager.GetString("LoginIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access token is missing.
        /// </summary>
        public static string MissingAccessToken {
            get {
                return ResourceManager.GetString("MissingAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing client_id.
        /// </summary>
        public static string MissingClientId {
            get {
                return ResourceManager.GetString("MissingClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client_id claim is missing.
        /// </summary>
        public static string MissingClientIdClaim {
            get {
                return ResourceManager.GetString("MissingClientIdClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the destination is empty.
        /// </summary>
        public static string MissingDestination {
            get {
                return ResourceManager.GetString("MissingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DPOP Proof is missing.
        /// </summary>
        public static string MissingDpopProof {
            get {
                return ResourceManager.GetString("MissingDpopProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_token_hint parameter is missing.
        /// </summary>
        public static string MissingIdTokenHint {
            get {
                return ResourceManager.GetString("MissingIdTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing parameter {0}.
        /// </summary>
        public static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing parameters {0}.
        /// </summary>
        public static string MissingParameters {
            get {
                return ResourceManager.GetString("MissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter post_logout_redirect_uri is missing.
        /// </summary>
        public static string MissingPostLogoutRedirectUri {
            get {
                return ResourceManager.GetString("MissingPostLogoutRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user doesn&apos;t have a registered mobile device.
        /// </summary>
        public static string MissingRegisteredUserDevice {
            get {
                return ResourceManager.GetString("MissingRegisteredUserDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid response type must be passed for the grant type {0}.
        /// </summary>
        public static string MissingResponseType {
            get {
                return ResourceManager.GetString("MissingResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the response_type claim is missing.
        /// </summary>
        public static string MissingResponseTypeClaim {
            get {
                return ResourceManager.GetString("MissingResponseTypeClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing response types {0}.
        /// </summary>
        public static string MissingResponseTypes {
            get {
                return ResourceManager.GetString("MissingResponseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the session identifier is missing.
        /// </summary>
        public static string MissingSessionId {
            get {
                return ResourceManager.GetString("MissingSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the subject cannot be extracted from the subject_token.
        /// </summary>
        public static string MissingSubSubjectToken {
            get {
                return ResourceManager.GetString("MissingSubSubjectToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing token.
        /// </summary>
        public static string MissingToken {
            get {
                return ResourceManager.GetString("MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter user_code is missing.
        /// </summary>
        public static string MissingUserCode {
            get {
                return ResourceManager.GetString("MissingUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no client secret.
        /// </summary>
        public static string NoClientSecret {
            get {
                return ResourceManager.GetString("NoClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no consent has been accepted.
        /// </summary>
        public static string NoConsent {
            get {
                return ResourceManager.GetString("NoConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no essential acr is supported.
        /// </summary>
        public static string NoEssentialAcrIsSupported {
            get {
                return ResourceManager.GetString("NoEssentialAcrIsSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no JWK with identifier {0} has been found to check the signature of the JWT.
        /// </summary>
        public static string NoJwkFoundToCheckSig {
            get {
                return ResourceManager.GetString("NoJwkFoundToCheckSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no JWK with identifier {0} has been found to decrypt the JWT.
        /// </summary>
        public static string NoJwkFoundToDecrypt {
            get {
                return ResourceManager.GetString("NoJwkFoundToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no JWK with algorithm {0} has been found to sign the JWT.
        /// </summary>
        public static string NoJwkWithAlgSig {
            get {
                return ResourceManager.GetString("NoJwkWithAlgSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no redirect uri has been registered.
        /// </summary>
        public static string NoRegisteredRedirectUrl {
            get {
                return ResourceManager.GetString("NoRegisteredRedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the incoming request doesn&apos;t contain a session_id.
        /// </summary>
        public static string NoSessionId {
            get {
                return ResourceManager.GetString("NoSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh token is expired.
        /// </summary>
        public static string RefreshTokenIsExpired {
            get {
                return ResourceManager.GetString("RefreshTokenIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh token has not been issued by the client.
        /// </summary>
        public static string RefreshTokenNotIssuedByClient {
            get {
                return ResourceManager.GetString("RefreshTokenNotIssuedByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you&apos;re not authorized to access to the permissions endpoint.
        /// </summary>
        public static string UnauthorizedAccessPermissionApi {
            get {
                return ResourceManager.GetString("UnauthorizedAccessPermissionApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the access token is not authorized to access to the operation.
        /// </summary>
        public static string UnauthorizedAccessToken {
            get {
                return ResourceManager.GetString("UnauthorizedAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unauthorized client.
        /// </summary>
        public static string UnauthorizedClient {
            get {
                return ResourceManager.GetString("UnauthorizedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client {0} is not authorized to access to perform operations on the grant.
        /// </summary>
        public static string UnauthorizedClientAccessGrant {
            get {
                return ResourceManager.GetString("UnauthorizedClientAccessGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unauthorized to scopes : {0}.
        /// </summary>
        public static string UnauthorizedScopes {
            get {
                return ResourceManager.GetString("UnauthorizedScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user {0} is not authorized to access to performance operations on the grant.
        /// </summary>
        public static string UnauthorizedUserAccessGrant {
            get {
                return ResourceManager.GetString("UnauthorizedUserAccessGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to either the access token has been revoked or is invalid.
        /// </summary>
        public static string UnknownAccessToken {
            get {
                return ResourceManager.GetString("UnknownAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the acr {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownAcr {
            get {
                return ResourceManager.GetString("UnknownAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the API resource {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownApiResource {
            get {
                return ResourceManager.GetString("UnknownApiResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to following audiences {0} don&apos;t exist.
        /// </summary>
        public static string UnknownAudience {
            get {
                return ResourceManager.GetString("UnknownAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown authentication method : {0}.
        /// </summary>
        public static string UnknownAuthMethod {
            get {
                return ResourceManager.GetString("UnknownAuthMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authentication methods {0} are unknown.
        /// </summary>
        public static string UnknownAuthMethods {
            get {
                return ResourceManager.GetString("UnknownAuthMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authentication scheme provider {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownAuthSchemeProvider {
            get {
                return ResourceManager.GetString("UnknownAuthSchemeProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authentication scheme provider cannot be updated because the following properties are unknown : {0}.
        /// </summary>
        public static string UnknownAuthSchemeProviderProperties {
            get {
                return ResourceManager.GetString("UnknownAuthSchemeProviderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the back channel authorization {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownBcAuthorize {
            get {
                return ResourceManager.GetString("UnknownBcAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown certificate authority {0}.
        /// </summary>
        public static string UnknownCa {
            get {
                return ResourceManager.GetString("UnknownCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown client {0}.
        /// </summary>
        public static string UnknownClient {
            get {
                return ResourceManager.GetString("UnknownClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown client certificate {0}.
        /// </summary>
        public static string UnknownClientCa {
            get {
                return ResourceManager.GetString("UnknownClientCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the credential offer doesn&apos;t exist.
        /// </summary>
        public static string UnknownCredentialOffer {
            get {
                return ResourceManager.GetString("UnknownCredentialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the device_code doesn&apos;t exist.
        /// </summary>
        public static string UnknownDeviceCode {
            get {
                return ResourceManager.GetString("UnknownDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the device {0} is not supported.
        /// </summary>
        public static string UnknownDeviceType {
            get {
                return ResourceManager.GetString("UnknownDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the grant {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownGrant {
            get {
                return ResourceManager.GetString("UnknownGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the group {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownGroup {
            get {
                return ResourceManager.GetString("UnknownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the group {0} don&apos;t exist.
        /// </summary>
        public static string UnknownGroupIds {
            get {
                return ResourceManager.GetString("UnknownGroupIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown role {0}.
        /// </summary>
        public static string UnknownGroupRole {
            get {
                return ResourceManager.GetString("UnknownGroupRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the identity provisioning {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownIdProvisioning {
            get {
                return ResourceManager.GetString("UnknownIdProvisioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the mapping rule {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownIdProvisioningMappingRule {
            get {
                return ResourceManager.GetString("UnknownIdProvisioningMappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the process {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownIdProvisioningProcess {
            get {
                return ResourceManager.GetString("UnknownIdProvisioningProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json Web Key doesn&apos;t exist.
        /// </summary>
        public static string UnknownJsonWebKey {
            get {
                return ResourceManager.GetString("UnknownJsonWebKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the permissions {0} don&apos;t exist.
        /// </summary>
        public static string UnknownPermissions {
            get {
                return ResourceManager.GetString("UnknownPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no registration workflow has been resolved.
        /// </summary>
        public static string UnknownRegistrationWorkflow {
            get {
                return ResourceManager.GetString("UnknownRegistrationWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to following resources {0} doesn&apos;t exist.
        /// </summary>
        public static string UnknownResource {
            get {
                return ResourceManager.GetString("UnknownResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown scope {0}.
        /// </summary>
        public static string UnknownScope {
            get {
                return ResourceManager.GetString("UnknownScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown scope claim mapper {0}.
        /// </summary>
        public static string UnknownScopeClaimMapper {
            get {
                return ResourceManager.GetString("UnknownScopeClaimMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scopes {0} are not present in the resource / audience.
        /// </summary>
        public static string UnknownScopeResourceOrAudience {
            get {
                return ResourceManager.GetString("UnknownScopeResourceOrAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown token type hint : {0}.
        /// </summary>
        public static string UnknownTokenTypeHint {
            get {
                return ResourceManager.GetString("UnknownTokenTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the UMA resource doesn&apos;t exist.
        /// </summary>
        public static string UnknownUmaResource {
            get {
                return ResourceManager.GetString("UnknownUmaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown user {0}.
        /// </summary>
        public static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown user&apos;s consent {0}.
        /// </summary>
        public static string UnknownUserConsent {
            get {
                return ResourceManager.GetString("UnknownUserConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown user&apos;s credential {0}.
        /// </summary>
        public static string UnknownUserCredential {
            get {
                return ResourceManager.GetString("UnknownUserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown user&apos;s external authentication provider.
        /// </summary>
        public static string UnknownUserExternalAuthProvider {
            get {
                return ResourceManager.GetString("UnknownUserExternalAuthProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown user&apos;s group {0}.
        /// </summary>
        public static string UnknownUserGroup {
            get {
                return ResourceManager.GetString("UnknownUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown user&apos;s session {0}.
        /// </summary>
        public static string UnknownUserSession {
            get {
                return ResourceManager.GetString("UnknownUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the actor type {0} is not supported.
        /// </summary>
        public static string UnsupportedActorType {
            get {
                return ResourceManager.GetString("UnsupportedActorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authentication method references {0} are not supported.
        /// </summary>
        public static string UnsupportedAmrs {
            get {
                return ResourceManager.GetString("UnsupportedAmrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization details types {0} are not supported.
        /// </summary>
        public static string UnsupportedAuthorizationDetailTypes {
            get {
                return ResourceManager.GetString("UnsupportedAuthorizationDetailTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization_encrypted_response_alg is not supported.
        /// </summary>
        public static string UnsupportedAuthorizationEncryptedResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedAuthorizationEncryptedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization_encrypted_response_enc is not supported.
        /// </summary>
        public static string UnsupportedAuthorizationEncryptedResponseEnc {
            get {
                return ResourceManager.GetString("UnsupportedAuthorizationEncryptedResponseEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization_signed_response_alg is not supported.
        /// </summary>
        public static string UnsupportedAuthorizationSignedResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedAuthorizationSignedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bc_authentication_request_signing_alg is not supported.
        /// </summary>
        public static string UnsupportedBcAuthenticationRequestSigningAlg {
            get {
                return ResourceManager.GetString("UnsupportedBcAuthenticationRequestSigningAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the credential type {0} is not supported.
        /// </summary>
        public static string UnsupportedCredentialType {
            get {
                return ResourceManager.GetString("UnsupportedCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the credential offer doesn&apos;t support those credential types {0}.
        /// </summary>
        public static string UnsupportedCredentialTypes {
            get {
                return ResourceManager.GetString("UnsupportedCredentialTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant type {0} is not supported.
        /// </summary>
        public static string UnsupportedGrantType {
            get {
                return ResourceManager.GetString("UnsupportedGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant types {0} are not supported.
        /// </summary>
        public static string UnsupportedGrantTypes {
            get {
                return ResourceManager.GetString("UnsupportedGrantTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_token_encrypted_response_alg is not supported.
        /// </summary>
        public static string UnsupportedIdTokenEncryptedResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedIdTokenEncryptedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_token_encrypted_response_enc is not supported.
        /// </summary>
        public static string UnsupportedIdTokenEncryptedResponseEnc {
            get {
                return ResourceManager.GetString("UnsupportedIdTokenEncryptedResponseEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_token_signed_response_alg is not supported.
        /// </summary>
        public static string UnsupportedIdTokenSignedResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedIdTokenSignedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the requested token type {0} is not supported.
        /// </summary>
        public static string UnsupportedRequestedTokenType {
            get {
                return ResourceManager.GetString("UnsupportedRequestedTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request_object_encryption_alg is not supported.
        /// </summary>
        public static string UnsupportedRequestObjectEncryptionAlg {
            get {
                return ResourceManager.GetString("UnsupportedRequestObjectEncryptionAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request_object_encryption_enc is not supported.
        /// </summary>
        public static string UnsupportedRequestObjectEncryptionEnc {
            get {
                return ResourceManager.GetString("UnsupportedRequestObjectEncryptionEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request_object_signing_alg is not supported.
        /// </summary>
        public static string UnsupportedRequestObjectSigningAlg {
            get {
                return ResourceManager.GetString("UnsupportedRequestObjectSigningAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the scheme provider {0} is not supported.
        /// </summary>
        public static string UnsupportedSchemeProvider {
            get {
                return ResourceManager.GetString("UnsupportedSchemeProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scopes {0} are not supported.
        /// </summary>
        public static string UnsupportedScopes {
            get {
                return ResourceManager.GetString("UnsupportedScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token_encrypted_response_alg is not supported.
        /// </summary>
        public static string UnsupportedTokenEncryptedResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedTokenEncryptedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token_encrypted_response_enc is not supported.
        /// </summary>
        public static string UnsupportedTokenEncryptedResponseEnc {
            get {
                return ResourceManager.GetString("UnsupportedTokenEncryptedResponseEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token_signed_response_alg is not supported.
        /// </summary>
        public static string UnsupportedTokenSignedResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedTokenSignedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the token type {0} is not supported.
        /// </summary>
        public static string UnsupportedTokenType {
            get {
                return ResourceManager.GetString("UnsupportedTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userinfo_encrypted_response_alg is not supported.
        /// </summary>
        public static string UnsupportedUserInfoEncryptedResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedUserInfoEncryptedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userinfo_encrypted_response_enc is not supported.
        /// </summary>
        public static string UnsupportedUserInfoEncryptedResponseEnc {
            get {
                return ResourceManager.GetString("UnsupportedUserInfoEncryptedResponseEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userinfo_signed_response_alg is not supported.
        /// </summary>
        public static string UnsupportedUserInfoSignResponseAlg {
            get {
                return ResourceManager.GetString("UnsupportedUserInfoSignResponseAlg", resourceCulture);
            }
        }
    }
}
